title: "Spress - Svbtle Theme"
description: "Svbtle Theme for Spress by @bitfalls"
logo: "spresso-logo.png"

# Your site's domain. E.g: http://yoursite.com
url: ""

parsedown_actived: true

# Comments in posts
comments:
    enabled: false
    disqus_shortname: ""

# Information about author
author:
    name: "Bruno Skvorc"

    # Social networks
    twitter: "bitfalls"
    github: "https://github.com/swader"
    bitbucket:
    facebook:
    linkedin:
    gplus:
    youtube:

# Collections
collections:
  posts:
    output: true

  projects:
    output: true

# RSS feed
feed:
    max_item: 10

# Facebook Open Graph
open_graph:
    locale: "en_US"

# Code highlight for <pre> and <code> tags
# Powered by http://highlightjs.org/
code_highlight: true

# Site validation
google_verify:
bing_verify:

# Page menus
top_menu:
    - { name: Home, url: "/" }
    - { name: Projects, url: "/projects" }

bottom_menu:
    - { name: "Read an awesome blog", url: "https://bitfalls.com" }
